# generated by Neptune Namespaces v3.x.x
# file: Art.Chat/Client/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Main:       require './Main'      
  Palette:    require './Palette'   
  StyleProps: require './StyleProps'
require './Components'