# generated by Neptune Namespaces v3.x.x
# file: Art.Chat/Client/Components/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Button:      require './Button'     
  ChatMessage: require './ChatMessage'
  ChatView:    require './ChatView'   
  Lobby:       require './Lobby'      