# generated by Neptune Namespaces v3.x.x
# file: Art.Chat/Client/Components/namespace.coffee

module.exports = (require '../namespace').addNamespace('Components', class Components extends Neptune.PackageNamespace)
