# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Chat/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.Chat', class Chat extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
