# generated by Neptune Namespaces v3.x.x
# file: Art.Chat/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  StandardImport: require './StandardImport'
require './Client'
require './Configs'
require './Pipelines'