# generated by Neptune Namespaces v3.x.x
# file: Art.Chat/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.Chat', class Chat extends Neptune.PackageNamespace
  @version: require('../../package.json').version
require './Client/namespace';
require './Configs/namespace';
require './Pipelines/namespace'